# development server properties
server:
  port: 8081

#h2 database properties
spring :
  datasource :
    driverClassName: org.h2.Driver
    url: "jdbc:h2:tcp://localhost/~/test"
    username: sa
    password:
    maxActive : 10
    maxIdle : 5
    minIdle : 2
    initialSize : 2
    removeAbandoned : true

# actuator properties
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always