# development server properties
server:
  port: 8081

#h2 database properties
spring :
  datasource :
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5433/postgres"
    username: kitefinder
    password: cezmeulmeuvrei
    maxActive : 10
    maxIdle : 5
    minIdle : 2
    initialSize : 2
    removeAbandoned : true

# actuator properties
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# application specific properties
fmak:
  supporter:
    tokens: test1,test2,test3